version: '3.4'

services:
  pdf_conversion:
    image: ${DOCKER_REGISTRY-}pdf_conversion
    build:
      context: .
      dockerfile: PdfConversion/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ~/.aspnet/https:/https:ro
